[package]
name = "ghostwriter"
version = "0.1.0"
edition = "2021"
[dependencies]
tokio = { version = "1.28", features = ["full"] }
ureq = { version = "2.6", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
base64 = "0.21"
image = "0.24"
